name: Daily devcard

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 17 * * *"

jobs:
  devcard:
    runs-on: ubuntu-latest
    steps:
      - uses: dailydotdev/action-devcard@2.3.1
        with:
          devcard_id: ${{ secrets.DEVCARD_ID }}
          commit_branch: "devcard"
          commit_message: "chore: update ${filename}"
