name: General metrics

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 17 * * *"

jobs:
  metrics-general:
    runs-on: ubuntu-latest
    steps:
      - name: Starred topics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.starred-topics.svg
          token: NOT_NEEDED
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
      - name: Fortune
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.fortune.svg
          token: NOT_NEEDED
          base: ""
          plugin_fortune: yes
      