name: Metrics

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 17 * * *"

jobs:
  github-metrics:
    name: Spotify - Top tracks
    steps:
      uses: lowlighter/metrics@latest
      with:
        token: NOT_NEEDED
        base: ""
        plugin_music: yes
        plugin_music_mode: top
        plugin_music_provider: spotify
        plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
        plugin_music_time_range: short
        plugin_music_top_type: tracks
