name: Metrics

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 17 * * 1" # Runs every monday at 7am Asia/HCM

jobs:
  metrics-spotify:
    runs-on: ubuntu-latest
    steps:
      - name: Spotify - Top tracks
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.top-tracks.svg
          token: NOT_NEEDED
          base: ""
          plugin_music: yes
          plugin_music_mode: top
          plugin_music_provider: spotify
          plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
          plugin_music_time_range: short
          plugin_music_top_type: tracks
          plugin_music_playlist: ${{ secrets.SPOTIFY_PLAYLIST_URL }}
          plugin_music_limit: 5
      - name: Spotify - Random tracks from playlist
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.random-tracks.svg
          token: NOT_NEEDED
          base: ""
          plugin_music: yes
          plugin_music_playlist: ${{ secrets.SPOTIFY_PLAYLIST_URL }}
          plugin_music_limit: 5
      